# Generated by Django 3.0.7 on 2020-07-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemegen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='Choice',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(default='no text', max_length=200),
            preserve_default=False,
        ),
    ]
