# Generated by Django 3.0.7 on 2020-07-07 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemegen', '0002_auto_20200708_0115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='question',
            new_name='choice',
        ),
    ]
