# Generated by Django 3.0.7 on 2020-07-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemegen', '0003_auto_20200708_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='text_repr',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
    ]
