# Generated by Django 3.0.7 on 2020-07-09 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schemegen', '0005_tree'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='tree',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schemegen.Tree'),
            preserve_default=False,
        ),
    ]
