# Generated by Django 3.0.7 on 2020-07-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemegen', '0007_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='multiple',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
