# Generated by Django 3.0.7 on 2020-07-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemegen', '0008_choice_multiple'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('header', models.TextField()),
                ('body', models.TextField()),
                ('footer', models.TextField()),
            ],
        ),
    ]
