# Generated by Django 3.0.7 on 2020-07-24 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemegen', '0010_textalias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schema',
            name='tree',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='choice',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Schema',
        ),
        migrations.DeleteModel(
            name='Tree',
        ),
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
